import test from 'node:test';
import assert from 'node:assert/strict';
import {createDeck,newRoom,startRound,applyAction as act,finishUnoTurn,viewFor,botAction,legalCard} from '../uno/engine.mjs';
import {encodeTicket,decodeTicket} from '../uno/transport.mjs';
import {Room} from '../uno/room.mjs';
// Baseline action tests explicitly expire the new UNO window; its live timing is tested separately.
function applyAction(...args){act(...args);finishUnoTurn(args[0]);}
function rng(seed = 1) { return n => { seed = (Math.imul(seed,1664525)+1013904223) >>> 0; return seed % n; }; }
function room(count = 3) { const s = newRoom({id:'a',name:'Alice'}); for (let i=1;i<count;i++) s.players.push({id:String(i),name:`Player ${i}`,hand:[],ready:true,connected:true,bot:true}); return s; }
function card(value,colour='red',id=value+colour) { return {id,value,colour}; }
function fixture(hand, top=card('5')) { const s=room(2); s.phase='playing';s.colour=top.colour;s.discard=[top];s.deck=[card('2','green')];s.players[0].hand=hand;s.players[1].hand=[card('8','blue'),card('3','yellow')];return s; }
function conserved(s) { const all=[...s.deck,...s.discard,...s.players.flatMap(p=>p.hand)]; assert.equal(all.length,108);assert.equal(new Set(all.map(c=>c.id)).size,108); }
test('108 unique cards; fair deck composition',()=>{const deck=createDeck();assert.equal(deck.length,108);assert.equal(new Set(deck.map(c=>c.id)).size,108);assert.equal(deck.filter(c=>c.colour==='wild').length,8);});
test('deal seven per seat, numeric opening, views hide every other hand and deck',()=>{const s=room(8);startRound(s,rng());conserved(s);for(const p of s.players){assert.equal(p.hand.length,7);const v=viewFor(s,p.id);assert.equal(v.hand.length,7);assert(!('deck'in v));assert(!('discard'in v));assert(v.players.every(q=>!('hand'in q)));assert.deepEqual(v.hand,p.hand);}});
test('illegal move and bad wild colour cannot mutate state',()=>{const s=fixture([card('9','blue'),card('wild','wild')]);const before=JSON.stringify(s);assert.throws(()=>applyAction(s,'a',{type:'play',cardId:'9blue'}));assert.equal(JSON.stringify(s),before);assert.throws(()=>applyAction(s,'a',{type:'play',cardId:'wildwild',colour:'purple'}));assert.equal(JSON.stringify(s),before);});
test('out of turn and disconnected players cannot play',()=>{const s=fixture([card('5','blue')]);assert.throws(()=>applyAction(s,'1',{type:'draw'}));s.players[0].connected=false;assert.throws(()=>applyAction(s,'a',{type:'draw'}));});
test('two player reverse skips opponent',()=>{const s=fixture([card('reverse'),card('4')]);applyAction(s,'a',{type:'play',cardId:'reversered'});assert.equal(s.turn,0);assert.equal(s.direction,-1);});
test('draw one: only drawn card can be played; pass advances',()=>{const s=fixture([card('5','blue')]);s.deck=[card('8','red')];applyAction(s,'a',{type:'draw'});assert.equal(s.drawn,'8red');assert(!legalCard(s,s.players[0],s.players[0].hand[0]));assert.throws(()=>applyAction(s,'a',{type:'draw'}));applyAction(s,'a',{type:'pass'});assert.equal(s.turn,1);});
test('wild +4 is forbidden with matching colour; no manual challenges',()=>{const s=fixture([card('draw4','wild'),card('9')]);assert(!legalCard(s,s.players[0],s.players[0].hand[0]));s.players[0].hand.pop();assert(legalCard(s,s.players[0],s.players[0].hand[0]));});
test('Draw Two stacking only accepts Draw Two and pays whole debt',()=>{const s=fixture([card('draw2'),card('4')]);s.rules.stack2=true;s.players[1].hand=[card('draw2','blue'),card('draw4','wild')];s.deck=Array.from({length:9},(_,i)=>card('3','green',`x${i}`));applyAction(s,'a',{type:'play',cardId:'draw2red'});assert.equal(s.debt,2);assert(!legalCard(s,s.players[1],s.players[1].hand[1]));applyAction(s,'1',{type:'play',cardId:'draw2blue'});assert.equal(s.debt,4);applyAction(s,'a',{type:'draw'});assert.equal(s.players[0].hand.length,5);assert.equal(s.debt,0);assert.equal(s.turn,1);});
test('seven swaps before win; zero rotates before win',()=>{const s=fixture([card('7')]);s.rules.sevenZero=true;assert.throws(()=>applyAction(s,'a',{type:'play',cardId:'7red'}));applyAction(s,'a',{type:'play',cardId:'7red',target:'1'});assert.equal(s.winner,'1');assert.equal(s.players[0].hand.length,2);const z=fixture([card('0')]);z.rules.sevenZero=true;applyAction(z,'a',{type:'play',cardId:'0red'});assert.equal(z.winner,'1');});
test('recycle preserves top discard',()=>{const s=fixture([card('8','blue')]);s.deck=[];s.discard=[card('3','green'),card('5')];applyAction(s,'a',{type:'draw'},rng());assert.equal(s.discard.length,1);assert.equal(s.discard[0].id,'5red');assert.equal(s.players[0].hand.length,2);});
test('seeded bot games finish with card conservation, all house-rule combinations',()=>{for(let seed=1;seed<=20;seed++){const s=room(2+seed%7),random=rng(seed);s.rules={stack2:!!(seed&1),sevenZero:!!(seed&2)};startRound(s,random);let turns=0;while(s.phase==='playing'&&turns++<10000){const id=s.players[s.turn].id;applyAction(s,id,botAction(s,id),random);conserved(s);}assert.equal(s.phase,'finished',`seed ${seed}`);assert(s.players.find(p=>p.id===s.winner).hand.length===0);}});
test('invite only accepts exact trusted iroh relays and protocol version',()=>{const t={v:3,host:'a'.repeat(64),relay:'https://aps1-1.relay.n0.iroh.link./',room:'a'.repeat(32),secret:'b'.repeat(32)};assert.deepEqual(decodeTicket(encodeTicket(t)),t);assert.deepEqual(decodeTicket(`https://example.test/uno/#join=${encodeTicket(t)}`),t);for(const bad of [{...t,v:1},{...t,v:2},{...t,relay:'https://127.0.0.1/'},{...t,relay:'https://evil.example/'},{...t,secret:''}])assert.throws(()=>decodeTicket(encodeTicket(bad)));assert.throws(()=>decodeTicket('x'.repeat(5000)));});
test('host authorization, stale commands, duplicate command acknowledgements',()=>{const events=[];const r=new Room({onView:()=>{},onStatus:()=>{},onError:()=>{}});r.isHost=true;r.self='a';r.state=room(2);r.ticket={room:'test',secret:'secret'};r.transport={disconnect:()=>{}};r.send=(id,m)=>events.push({id,...m});r.broadcast=()=>{};r.peers.set('c',{seat:'1',count:0,window:Date.now(),lastSeen:Date.now()});r.seats.set('1',{secret:'resume',commands:new Map()});assert.throws(()=>r.execute('1',{type:'start'}));startRound(r.state,rng());r.state.turn=1;const rev=r.state.revision;const m={type:'command',id:'a'.repeat(32),revision:rev,action:{type:'draw'}};r.hostMessage('c',m);const after=JSON.stringify(r.state);r.hostMessage('c',m);assert.equal(JSON.stringify(r.state),after);assert.equal(events.filter(e=>e.type==='ack').length,2);assert.throws(()=>r.execute('1',{type:'draw'},rev));});
