import test from 'node:test';
import assert from 'node:assert/strict';
import {newRoom,applyAction,viewFor} from '../uno/engine.mjs';
import {TablePresentation,presentationFrames,effectDuration,TIMING} from '../uno/presentation.mjs';
import {Room} from '../uno/room.mjs';
const card=(id,value,colour='red')=>({id,value,colour});
function fixture(){const s=newRoom({id:'a',name:'Alice'});s.players[0].hand=[card('a1','3'),card('a2','2','blue')];for(const id of ['b','c'])s.players.push({id,name:id,hand:[card(id+'1','8','green'),card(id+'2','4','blue')],connected:true,ready:true,bot:false});s.phase='playing';s.colour='red';s.discard=[card('top','5')];s.deck=[card('d1','9'),card('d2','2','green'),card('d3','3','blue')];return s;}
function room(s=fixture()){const r=new Room({onView:()=>{},onStatus:()=>{},onError:()=>{}});r.self='a';r.isHost=true;r.state=s;r.send=()=>{};return r;}
test('draw effects retain order and never expose another hand or drawn identity',()=>{const s=fixture();s.rules.drawUntilPlayable=true;const before=viewFor(s,'a'),remoteBefore=viewFor(s,'b');applyAction(s,'a',{type:'draw'});const own=viewFor(s,'a'),other=viewFor(s,'b');assert.deepEqual(own.effects.events[0].cards.map(c=>c.id),['d3','d2','d1']);assert.deepEqual(other.effects.events[0],{kind:'draw',player:'a',count:3});const frames=presentationFrames(before,own);assert.deepEqual(frames.map(f=>f.view.hand.length),[3,4,5,5]);assert(frames.every(f=>f.view.legal.length===0&&f.duration>=TIMING.settle&&f.view.drawn===null));assert.deepEqual(presentationFrames(remoteBefore,other).map(f=>f.view.players[0].count),[3,4,5,5]);assert(presentationFrames(remoteBefore,other).every(f=>f.view.hand.every(c=>c.id.startsWith('b'))));own.effects.events[0].cards[0].colour='purple';assert.equal(s.effects.events[0].cards[0].colour,'blue');});
test('forced draw is presented before its automatic play, not teleported to discard',()=>{const s=fixture();s.rules.drawUntilPlayable=s.rules.forcePlay=true;const before=viewFor(s,'a');applyAction(s,'a',{type:'draw'});const v=viewFor(s,'a'),frames=presentationFrames(before,v);assert.deepEqual(v.effects.events.map(e=>e.kind),['draw','play']);assert.deepEqual(frames.map(f=>f.view.hand.length),[3,4,5,4,4]);assert.equal(frames[2].view.hand.at(-1).id,'d1');assert.equal(frames[3].view.top.id,'d1');});
test('7 identifies the actual actor/target and separates selection, both flights and the pause',()=>{const s=fixture();s.rules.sevenZero=true;s.players[0].hand[0]=card('seven','7');const before=viewFor(s,'a');applyAction(s,'a',{type:'play',cardId:'seven',target:'b'});const v=viewFor(s,'a'),frames=presentationFrames(before,v);assert.deepEqual(v.effects.events[1],{kind:'swap',from:'a',to:'b'});assert.deepEqual(frames.map(f=>f.view.presentation.phase||f.view.presentation.kind),['play','select','outbound','pause','inbound','settle','settle']);assert.equal(frames[3].duration,TIMING.pause);assert.equal(frames[4].view.hand[0].id,'a2');assert.deepEqual(frames[5].view.hand,v.hand);assert.equal(effectDuration(v.effects),frames.reduce((n,f)=>n+f.duration,0));});
test('host gates animations and normal turns during jump-in window, while accepting a legal jumper',()=>{const s=fixture();s.rules.jumpIn=true;s.players[0].hand[0]=card('play','5');s.players[2].hand[0]=card('jump','5');s.players[0].hand.push(card('extra-a','9'));s.players[2].hand.push(card('extra-c','9'));const r=room(s);r.execute('a',{type:'play',cardId:'play'},s.revision);const before=JSON.stringify(s);assert.throws(()=>r.execute('b',{type:'draw'},s.revision),/moving/);assert.equal(JSON.stringify(s),before);r.actionTiming.revealUntil=performance.now()-1;assert.throws(()=>r.execute('b',{type:'draw'},s.revision),/Jump-in window/);r.execute('c',{type:'play',cardId:'jump'},s.revision);assert.equal(s.lastPlayedBy,'c');assert.equal(s.turn,0);});
test('forced penalties are automatic only if no legal stacking decision exists',()=>{const s=fixture();s.debt=2;s.discard=[card('top','draw2')];const r=room(s);assert.equal(r.snapshotFor('a').autoDraw,true);s.rules.stack2=true;s.players[0].hand.push(card('stack','draw2','blue'));assert.equal(r.snapshotFor('a').autoDraw,false);s.players[0].hand.at(-1).value='draw4';assert.equal(r.snapshotFor('a').autoDraw,true);s.players[0].connected=false;assert.equal(r.snapshotFor('a').autoDraw,false);});
test('a normal turn with no legal play automatically draws, but a playable hand keeps its choice',()=>{const s=fixture(),r=room(s);assert.equal(r.snapshotFor('a').autoDraw,false);s.players[0].hand=[card('only','2','blue')];assert.equal(r.snapshotFor('a').autoDraw,true);s.drawn='only';assert.equal(r.snapshotFor('a').autoDraw,false);});
test('latency clears on reconnect and stop instead of displaying a stale measured number',async()=>{const r=room();r.latency={b:120};r.reconnect();assert.deepEqual(r.latency,{});r.latency={b:80};await r.stop();assert.deepEqual(r.latency,{});});
test('presentation queues revisions, ignores duplicate events and cancels timers on disconnect',t=>{
 t.mock.timers.enable({apis:['setTimeout']});const s=fixture(),seen=[];
 const presenter=new TablePresentation((view,online,pending,busy)=>seen.push({view,online,pending,busy}));
 presenter.receive(viewFor(s,'a'));s.rules.drawUntilPlayable=true;applyAction(s,'a',{type:'draw'});const drawn=viewFor(s,'a');
 presenter.receive(drawn);assert.equal(seen.at(-1).view.hand.length,3);const count=seen.length;
 presenter.receive(drawn);assert.equal(seen.length,count,'duplicate snapshot cannot restart an animation');
 t.mock.timers.tick(TIMING.draw);assert.equal(seen.at(-1).view.hand.length,4);
 applyAction(s,'a',{type:'pass'});const next=viewFor(s,'a');presenter.receive(next);
 t.mock.timers.tick(TIMING.draw);assert.equal(seen.at(-1).view.hand.length,5);
 t.mock.timers.tick(TIMING.draw);t.mock.timers.tick(TIMING.settle);t.mock.timers.tick(TIMING.settle);assert.equal(seen.at(-1).view.revision,next.revision);assert.equal(seen.at(-1).busy,false);
 presenter.reset();presenter.receive({...next,revealMs:1000});assert.equal(seen.at(-1).busy,true);
 presenter.receive(next,false);const stopped=seen.length;assert.equal(seen.at(-1).online,false);
 t.mock.timers.tick(5000);assert.equal(seen.length,stopped);presenter.reset();
});
test('a new jump-in revision interrupts the presentation window without replaying the prior card',t=>{
 t.mock.timers.enable({apis:['setTimeout']});const s=fixture(),seen=[];
 s.rules.jumpIn=true;s.players[0].hand[0]=card('play','5');s.players[2].hand[0]=card('jump','5');s.players[0].hand.push(card('extra-a','9'));s.players[2].hand.push(card('extra-c','9'));
 const presenter=new TablePresentation((view,online,pending,busy)=>seen.push({view,busy}));presenter.receive(viewFor(s,'c'));
 applyAction(s,'a',{type:'play',cardId:'play'});presenter.receive({...viewFor(s,'c'),jumpWindowMs:TIMING.play+TIMING.settle+TIMING.jump});
 t.mock.timers.tick(TIMING.play);t.mock.timers.tick(TIMING.settle);assert.equal(seen.at(-1).view.presentation.kind,'jump-window');assert.equal(seen.at(-1).busy,false);assert(seen.at(-1).view.legal.includes('jump'));
 applyAction(s,'c',{type:'play',cardId:'jump'});presenter.receive(viewFor(s,'c'));assert.equal(seen.at(-1).view.top.id,'jump');assert.equal(seen.at(-1).busy,true);
 t.mock.timers.tick(TIMING.play);t.mock.timers.tick(TIMING.settle);const final=seen.length;t.mock.timers.tick(3000);assert.equal(seen.length,final);assert.equal(seen.at(-1).view.top.id,'jump');presenter.reset();
});
test('numeric latency accepts only the locally issued matching nonce, without changing game revision',()=>{const r=room(),p={seat:'b',count:0,window:Date.now(),probe:{nonce:'expected',start:performance.now()-120}};r.peers.set('connection',p);const revision=r.state.revision;r.hostMessage('connection',{type:'pong',nonce:'forged'});assert.equal(p.rtt,undefined);r.hostMessage('connection',{type:'pong',nonce:'expected'});assert(p.rtt>=120&&p.rtt<1000);assert.equal(r.latency.a,0);assert.equal(r.latency.b,p.rtt);assert.equal(r.latency.c,null);assert.equal(r.state.revision,revision);});
