import test from 'node:test';
import assert from 'node:assert/strict';
import {newRoom,startRound,applyAction as act,finishUnoTurn,viewFor,legalCard,botAction} from '../uno/engine.mjs';
import {RULES,DEFAULT_RULES,validateRules} from '../uno/rules.mjs';
import {nextAvatar,validateAvatar} from '../uno/profiles.mjs';
import {Room} from '../uno/room.mjs';
// Expire post-play call windows in baseline rule simulations; release tests cover real gates.
function applyAction(...args){act(...args);finishUnoTurn(args[0]);}
const card=(value,colour='red',id=`${colour}-${value}`)=>({id,value,colour});
function state(count=3){const s=newRoom({id:'a',name:'Alice'});for(let i=1;i<count;i++)s.players.push({id:String(i),name:`Player ${i}`,avatar:nextAvatar(s.players),hand:[card('8','green',`hand-${i}`)],ready:true,connected:true,bot:false});s.players[0].hand=[card('3')];s.phase='playing';s.discard=[card('5')];s.colour='red';return s;}
const unchanged=(s,fn)=>{const before=JSON.stringify(s);assert.throws(fn);assert.equal(JSON.stringify(s),before);};
const rng=(seed=1)=>n=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed%n;};
test('five independent boolean rules; invalid input cannot silently coerce values',()=>{assert.equal(RULES.length,5);for(const {key} of RULES){const r=validateRules({...DEFAULT_RULES,[key]:true});assert.equal(Object.values(r).filter(Boolean).length,1);}assert.throws(()=>validateRules({...DEFAULT_RULES,forcePlay:'false'}));assert.throws(()=>validateRules({stack2:true}));});
test('jump-in steals the turn only for an exact colour and number, then advances from the jumper',()=>{const s=state(4);s.players[2].hand=[card('5','red','jump'),card('9','blue')];assert(!legalCard(s,s.players[2],s.players[2].hand[0]));s.rules.jumpIn=true;assert(legalCard(s,s.players[2],s.players[2].hand[0]));assert(!legalCard(s,s.players[1],card('5','blue')));applyAction(s,'2',{type:'play',cardId:'jump'});assert.equal(s.turn,3);assert.equal(s.lastPlayedBy,'2');assert.match(s.notice,/jumped in/);});
test('jump-ins are blocked for actions, wilds, penalties, a drawn choice, and a disconnected current player',()=>{const s=state();s.rules.jumpIn=true;const p=s.players[1];s.discard=[card('skip')];assert(!legalCard(s,p,card('skip')));s.discard=[card('wild','wild')];assert(!legalCard(s,p,card('wild','wild')));s.discard=[card('5')];for(const key of ['debt','drawn']){s[key]=1;assert(!legalCard(s,p,card('5')));s[key]=null;}s.players[0].connected=false;assert(!legalCard(s,p,card('5')));});
test('7 jump-in requires a validated swap target before any turn/hand mutation',()=>{const s=state();s.rules={...DEFAULT_RULES,jumpIn:true,sevenZero:true};s.discard=[card('7','red','top')];s.players[1].hand=[card('7'),card('4','blue')];unchanged(s,()=>applyAction(s,'1',{type:'play',cardId:'red-7'}));applyAction(s,'1',{type:'play',cardId:'red-7',target:'2'});assert.equal(s.players[1].hand[0].id,'hand-2');assert.equal(s.turn,2);});
test('draw till playable stops at the first new match, leaves older cards unplayable, and allows pass independently',()=>{const s=state();s.rules.drawUntilPlayable=true;s.deck=[card('9','red'),card('2','blue'),card('4','green')];applyAction(s,'a',{type:'draw'});assert.equal(s.drawn,'red-9');assert.equal(s.players[0].hand.length,4);assert(!legalCard(s,s.players[0],s.players[0].hand[0]));assert.deepEqual(viewFor(s,'a').legal,['red-9']);applyAction(s,'a',{type:'pass'});assert.equal(s.turn,1);});
test('draw till playable terminates when draw/recycle supply is exhausted',()=>{const s=state();s.rules.drawUntilPlayable=true;s.deck=[card('2','blue')];applyAction(s,'a',{type:'draw'});assert.equal(s.turn,1);assert.equal(s.deck.length,0);assert.equal(s.drawn,null);assert.equal(s.discard.length,1);});
test('force play automatically plays normal drawn cards in a single revision, without enabling draw-till',()=>{const s=state();s.rules.forcePlay=true;s.deck=[card('2','blue'),card('reverse')];const revision=s.revision;applyAction(s,'a',{type:'draw'});assert.equal(s.revision,revision+2);assert.equal(s.discard.at(-1).value,'reverse');assert.equal(s.direction,-1);assert.equal(s.turn,2);assert.equal(s.deck.length,1);const n=state();n.rules.forcePlay=true;n.deck=[card('2','red'),card('6','blue')];applyAction(n,'a',{type:'draw'});assert.equal(n.deck.length,1);assert.equal(n.turn,1);});
test('force play + draw till playable combine, but penalties never auto-play or trigger extra draws',()=>{const s=state();s.rules={...DEFAULT_RULES,forcePlay:true,drawUntilPlayable:true};s.deck=[card('9'),card('2','blue')];applyAction(s,'a',{type:'draw'});assert.equal(s.discard.at(-1).value,'9');assert.equal(s.turn,1);const p=state();p.rules={...s.rules};p.debt=2;p.deck=[card('9'),card('2'),card('3','blue')];applyAction(p,'a',{type:'draw'});assert.equal(p.deck.length,1);assert.equal(p.discard.at(-1).value,'5');assert.equal(p.debt,0);assert.equal(p.turn,1);});
test('forced wild and 7 draws require choices, reject pass atomically, and still permit choosing',()=>{for(const drawn of [card('wild','wild'),card('7')]){const s=state();s.rules.forcePlay=true;s.rules.sevenZero=true;s.deck=[drawn];applyAction(s,'a',{type:'draw'});assert.equal(s.drawn,drawn.id);unchanged(s,()=>applyAction(s,'a',{type:'pass'}));unchanged(s,()=>applyAction(s,'a',{type:'play',cardId:drawn.id}));applyAction(s,'a',{type:'play',cardId:drawn.id,colour:'blue',target:'1'});assert.equal(s.discard.at(-1).id,drawn.id);}});
test('+4 stacks on +4, never mixes with +2, and collects the full debt',()=>{const s=state();s.rules.stack2=true;s.discard=[card('draw4','wild','top')];s.debt=4;s.players[0].hand=[card('draw4','wild'),card('3')];s.deck=Array.from({length:10},(_,i)=>card('1','blue',`deck-${i}`));assert(!legalCard(s,s.players[0],card('draw2')));applyAction(s,'a',{type:'play',cardId:'wild-draw4',colour:'green'});assert.equal(s.debt,8);applyAction(s,'1',{type:'draw'});assert.equal(s.players[1].hand.length,9);assert.equal(s.debt,0);});
test('all 32 rule combinations finish seeded 2–8 player games and conserve 108 distinct cards, including jump-ins',()=>{for(let mask=0;mask<32;mask++){const s=state(2+mask%7),random=rng(mask+41);s.phase='lobby';s.rules=Object.fromEntries(RULES.map(({key},i)=>[key,!!(mask&(1<<i))]));startRound(s,random);let turns=0;while(s.phase==='playing'&&turns++<15000){const jump=s.rules.jumpIn&&turns%4===0?s.players.find(p=>p.id!==s.players[s.turn].id&&p.hand.some(c=>legalCard(s,p,c))):null;const actor=jump||s.players[s.turn];applyAction(s,actor.id,botAction(s,actor.id),random);const all=[...s.deck,...s.discard,...s.players.flatMap(p=>p.hand)];assert.equal(all.length,108);assert.equal(new Set(all.map(c=>c.id)).size,108);}assert.equal(s.phase,'finished',`rule mask ${mask}`);}});
test('eight automatic avatars are distinct, removed slots can be reused, and profiles contain no arbitrary CSS/URLs',()=>{const players=[];for(let i=0;i<8;i++)players.push({avatar:nextAvatar(players)});assert.equal(new Set(players.map(p=>JSON.stringify(p.avatar))).size,8);const removed=players.splice(3,1)[0];assert.deepEqual(nextAvatar(players),removed.avatar);assert.throws(()=>validateAvatar({colour:'url(https://example.test)',pattern:'dots'}));assert.throws(()=>validateAvatar({colour:'red',pattern:'../private'}));assert.deepEqual(validateAvatar({colour:'red',pattern:'waves',url:'https://example.test'}),{colour:'red',pattern:'waves'});});
test('self-only profile commands validate atomically, retain readiness/seat, and lock during rounds',()=>{const r=new Room({onView:()=>{},onStatus:()=>{},onError:()=>{}});r.self='a';r.state=state();r.state.phase='lobby';const before=r.state.players[0];r.execute('1',{type:'profile',name:' New name ',avatar:{colour:'teal',pattern:'rings'}});assert.equal(r.state.players[1].name,'New name');assert.equal(r.state.players[1].ready,true);assert.equal(r.state.players[0],before);for(const action of [{name:' '},{avatar:{colour:'evil',pattern:'dots'}},{target:'a'}])unchanged(r.state,()=>r.execute('1',{type:'profile',name:'Valid',avatar:{colour:'blue',pattern:'dots'},...action}));r.state.phase='playing';unchanged(r.state,()=>r.execute('1',{type:'profile',name:'Blocked',avatar:{colour:'blue',pattern:'dots'}}));const v=viewFor(r.state,'1');v.players[1].avatar.colour='red';assert.equal(r.state.players[1].avatar.colour,'teal');});
test('host-only rule changes reset guest readiness and lock during a round without mutating on validation failure',()=>{const r=new Room({onView:()=>{},onStatus:()=>{},onError:()=>{}});r.self='a';r.state=state();r.state.phase='lobby';unchanged(r.state,()=>r.execute('1',{type:'rules',...DEFAULT_RULES,jumpIn:true}));unchanged(r.state,()=>r.execute('a',{type:'rules',...DEFAULT_RULES,jumpIn:'yes'}));r.execute('a',{type:'rules',...DEFAULT_RULES,jumpIn:true});assert.equal(r.state.players[1].ready,false);assert.equal(r.state.rules.jumpIn,true);assert.equal(r.state.rules.forcePlay,false);r.state.phase='playing';unchanged(r.state,()=>r.execute('a',{type:'rules',...DEFAULT_RULES}));});
